[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/milosgajdos83/tenus"
  revision = "955dc12ecd6022db7dc161ff2fc07a2191bd98ae"

[[constraint]]
  name = "github.com/apparentlymart/go-cidr"
  version = "1.0.0"
